sudo: required
language: bash

services:
  - docker

cache:
  directories:
  - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      env:
        - VM=ubuntu
        - TAG=18.04
    - os: linux
      env: 
        - VM=mxe-w32-ubuntu
        - TAG=18.04
    - os: osx
      compiler: clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install qt5 qbs net-snmp ;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull fwbuilder/$VM:$TAG ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run -v $(pwd):/root -it fwbuilder/$VM:$TAG "docker/travis.${VM}_${TAG}.sh" ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH="/usr/local/opt/qt/bin:/usr/local/opt/net-snmp/bin:$PATH" ;
      ./build_mac.sh all ;
    fi

